---
- name: install jdk
  yum:
   name: java-1.6.0-openjdk-devel
   state: present
   
- name: add port 9990 to firewall exception
  firewalld:
   port: 9990/tcp
   permanent: yes
   state: enabled
   
- name: create jboss directory
  file:
   state: directory
   path: /tmp/ansible
  
- name: download jboss package
  get_url:
   url: http://download.jboss.org/jbossas/7.1/jboss-as-7.1.1.Final/jboss-as-7.1.1.Final.tar.gz
   dest: /tmp/ansible
   
- name: unzip jboss package
  unarchive:
   src: /tmp/ansible/jboss-as-7.1.1.Final.tar.gz
   dest: /tmp/ansible
   remote_src: yes
   
- name: execute standalone.sh script
  script: /tmp/ansible/jboss-as-7.1.1.Final/bin/standalone.sh
    
